### ISSUE TITLE
sitemap_to_df cannot handle multiple images

### ISSUE THREAD

**Issue by naidu-rohit** [eliasdabbas/advertools#108]
sitemap_to_df only returns the first image loc in the sitemap. If there are multiple images it ignores them. example https://www.levi.in/sitemap_0.xml

How can we make this work for multiple images?

**Comment by eliasdabbas** [comment]
True. This is exactly like #87  the issue of multiple video tags when available, as well as hreflang (not implemented yet). 
I'm still considering different ways of doing this because you will have multiple values for each row in the returned DataFrame. 
For now, it seems like multiple values will be delimited by `@@` like in the crawl function, and be placed in the same cell. 
 Let me know if you have other suggestions.

**Comment by naidu-rohit** [comment]
I was thinking we can keep images and videos in a separate dataframe with loc as key. So we can have multiple images for each loc.

**Comment by eliasdabbas** [comment]
Similar to  #87, to be handled for all types of multiple items in sitemaps.
