### ISSUE TITLE
Getting NaN values for serp_goog function

### ISSUE THREAD

**Issue by kzaman1** [eliasdabbas/advertools#238]
I tried running the following query:
df = adv.serp_goog(q=search_term, cx=cse_id, key=api_key)

However, it just returns a bunch of NaN values for rank, title, snippet, displaylink, link
![image](https://user-images.githubusercontent.com/12433436/193903883-f9330de7-cb2b-4089-8bb5-185fc85c4b03.png)

**Comment by eliasdabbas** [comment]
Thanks for reporting @kzaman1 

The `totalResults` column shows zero results. So, having `NaN` is consistent with that. 

It's still strange because there should be lots of results for "halal investing".

What other arguments did you provide to the function? Maybe it's a combination that doesn't have results?

**Comment by kzaman1** [comment]
Thanks for the super fast response! It actually wasn't an issue with the avertools package, my Custom Google Search settings weren't enabled for 'searching the entire web'. It's working great now!

![image](https://user-images.githubusercontent.com/12433436/193947956-68252fd9-66f0-49b7-a23a-e9df26332271.png)

Great package btw!

**Comment by eliasdabbas** [comment]
Great!
Thanks for letting me know, and glad you like it.
