### ISSUE TITLE
Suggestion - don't treat jsonld items in distinct script tags as distinct.

### ISSUE THREAD

**Issue by dreaded369** [eliasdabbas/advertools#255]
Some field observations with a small data set of only 12 sites:
8 place all their json-ld tags in a hierarchy under @graph (wrapped in a single script tag), and 4 spread place their items in seperate script tags.
advertools treats each occurrence of as a seperate entity, so for those in a hierarchy there is a single json-dl @graph column with nested object, and those without a hierachy get spread out over multiple columns (json_1_ etc...).

I'm building a scraper that regularly and often scrapes the same sites. With the current functionaly of advertools I will need to inspect each site and write conditions to scrape columns depending on how json-ld tags have been stored.

I think it would be helpful to treat json-ld items, whether they are in a hierachy under @graph or in distinct script tags, as being equal. As far as I can tell the only difference apart from being nested is that the @context entry appears as a sibling to @graph and so only appears once in the whole scheme.

NESTED:
{
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "WebSite",
      ...

NON-NESTED:
{
  "@context": "http:\/\/schema.org",
  "@type": "Website",
  ...

Then as a bonus break out each @type to a column with the whole record within.

**Comment by dreaded369** [comment]
I think columns like this would be much more useful than the way it's currently broken out:
jsonld(all), json@type_Website, jsonld@type_Person, jsonld@type_Article etc...

And I've just thought - now I've got conditions in my code - for site X grab column jsonld_2_title - but that breaks if the order of their tags change for any reason.

**Comment by eliasdabbas** [comment]
Tanks @dreadedhamish. Some notes:

* Breaking JSON-LD scripts contains the meaning that each number signifies how the code is split/placed on the page. This makes it easy for the analyst to understand how things are organized. Item A belongs to the first script with item B, and item C is in a different script, etc.
* Nested items *are* split into separate columns already
* Some items contain more than one element, and are presented as a list. This is why they are in one place (cell). For example, if you have `sameAs`, under that you might have a list of entities (a URL, a Twitter profile, and so on). So, this is essentially one "item".

>As far as I can tell the only difference apart from being nested is that the @context entry appears as a sibling to @graph and so only appears once in the whole scheme.

This might have been the case in the sites you crawled, but there are literally endless possibilities.

One possible change is to treat the listed items like other multiple elements, split by "@@". For example: `h3_1@@h3_2@@h3__3`
The problem here is, what if one of the listed items contains a list? How deep does this go? 

What do you think?

**Comment by dreaded369** [comment]
I get it - advertools currently is prioritising the 'how' rather than 'what' of content on a page. I can see how that would be very beneficial for certain projects.
I added a custom Xpath selector: 'allJSON': '//script[@type="application/ld+json"]//text()', (and currently trying to figure out how to so a split to list on a dataframe column, before parsing the different elements to new columns). 
I think adding an all_jsonld as standard would be helpful, and maybe add a section to the docs with some hints for a more content focused approach.
As far as depth - what's the longest hson-ld you've seen? It wouldn't worry me but Im sure there are edge-cases that could bring the whole system to it's knees.

**Comment by eliasdabbas** [comment]
> advertools currently is prioritising the 'how' rather than 'what' of content on a page

I'd say it's more about making it easier to understand/analyze the crawled website. Whatever helps that, I'm all for it.

> how to so a split to list on a dataframe column

Currently, there is a helper function for parsing JSON-LD. [_json_to_dict](https://github.com/eliasdabbas/advertools/blob/dee48b7c874cb896fff9e0c58fdb0d048254ac1d/advertools/spider.py#L586) , and converting to a dict. Check it out, we can work on improving it.

> what's the longest hson-ld you've seen?

I don't remember, but it's a big risk to make assumptions that might result in errors.

This JSON-LD that exists on a page as a list is annoying, and causes other issues, like converting to parquet, it gets messy.

I'd love to find a better way to handle it. 

If you want we can start with a sample JSON-LD script, and check the various ways of parsing it?

**Comment by eliasdabbas** [comment]
@dreadedhamish Some great/horrible examples, since you asked :) 


This crawl file has sixty JSON-LD columns: 

<img width="989" alt="Screen Shot 2022-12-23 at 10 57 27 PM" src="https://user-images.githubusercontent.com/15708966/209400718-18f3a2fc-a95c-4ef7-ab08-fb6594cfcc28.png">

That column looks nested... 
How nested??

<img width="1364" alt="Screen Shot 2022-12-23 at 10 59 34 PM" src="https://user-images.githubusercontent.com/15708966/209400810-912c0b00-620d-4715-9c59-7ced05033ce9.png">

Expand column 0 after expanding `jsonld_mainEntity.mentions`:

<img width="1085" alt="Screen Shot 2022-12-23 at 10 48 41 PM" src="https://user-images.githubusercontent.com/15708966/209400886-686296db-aed8-4945-b3bc-8675a8ad9fb1.png">


Do the same to column 1: 

<img width="1269" alt="Screen Shot 2022-12-23 at 10 48 51 PM" src="https://user-images.githubusercontent.com/15708966/209400957-2bfa7b3d-3986-4926-a58c-f10bb69d96fc.png">


Thoughts, suggestions?

**Comment by dreaded369** [comment]
Wow. 
okay - how about a helper function for jsonld types, with a parameter for levels of nesting?
Like an xpath selector, but instead you'd select a value for @type, and specify a level of nesting - so only include key/values at a maximum depth of 2.

I'll post how I've dealt with it (partially) when I'm back at my computer - i had trouble using split on a column, and then sometimes there were extra spaces and carriage returns around the @@ - but I'm newish at dataframes so these issues ight not be a big deal for most. If this helper function could add items to a list rather than splitting with @@ that would help others like me in the future.

**Comment by eliasdabbas** [comment]
> Like an xpath selector, but instead you'd select a value for @type, and specify a level of nesting - so only include key/values at a maximum depth of 2.

This can be done, but it's a very specific case, and might not suit everyone. We can still explore it and share.

In any case, the full data are available and accessible, and getting familiar with dataframes and pandas can help a lot. 

I made this thread also to explain a bit more about how JSON-LD data gets arranged, and how to parse it (based on the above data):

https://twitter.com/eliasdabbas/status/1606600074250915840

**Comment by eliasdabbas** [comment]
Closing as there doesn't seem to be a problem. All data can be extracted correctly, but in many cases it requires a bit more coding.
Feel free to re-open if you have other ideas/suggestions. 
Thanks again.
