### ISSUE TITLE
How to get initial url in output.jl ?

### ISSUE THREAD

**Issue by caroheymes** [eliasdabbas/advertools#259]
Hello Elias, 

Advertools is a really great package ! Many thanks for the splendid work.

Nevertheless I have a little problem for which I have not found a good workaround (except crawling urls one by one)

I was wondering how to get the initial url that is crawled. 
Advertools returns the url after redirection and not the url before.  So when you want to merge data it can becone tricky if you have no "reference".

Can we also imagine to "inject" specific user params as string  to get them in the output ? I've tried to do so in the xpath_selectors, but completely failed.

Many thanks,

Caro

**Comment by eliasdabbas** [comment]
Thanks a lot @caroheymes 
Glad you're using it! 

This is a very important issue. Good news, the solution already exists (in all crawl files you have already). Maybe I should do a better job documenting and explaining. 

In the crawl df, `url` refers to the crawled URL (downloaded, parsed, and its elements saved to a file on disk), but as you know it might not be the URL that was _requested_. This typically happens where there are redirects. The issue is that we might have one, two, three, or even more redirects.

Example: 

```python
import pandas as pd
crawl_df = pd.read_json('output_file.jl', lines=True)
crawl_df.filter(regex='^url$|redirect_').dropna()
```

|    | url                                            |   redirect_times |   redirect_ttl | redirect_urls                                                                                   | redirect_reasons   |
|---:|:-----------------------------------------------|-----------------:|---------------:|:------------------------------------------------------------------------------------------------|:-------------------|
|  0 | https://www.nytimes.com/                       |                1 |             19 | https://nytimes.com/                                                                             | 301                |
| 83 | https://www.nytimes.com/newsletters/realestate |                2 |             18 | http://www.nytimes.com/newsletters/realestate/@@https://www.nytimes.com/newsletters/realestate/ | 301@@301           |


The `redirect_urls` column contains all URLs requested and redirected, leading finally to `url`. In the first row we have one redirect (301), and in the second we have two. We also have the full redirect chain in both rows (one in the first and two in the second). So you can also see intermediate pages if any.

As all other columns, multiple values are separated by `@@`. 

I hope this clarifies it.

**Comment by eliasdabbas** [comment]
Assuming the question is answered. Feel free to re-open if you have other questions on this topic.
