### ISSUE TITLE
logs_to_df() Limitation

### ISSUE THREAD

**Issue by Dibal** [eliasdabbas/advertools#334]
## 1) Missing domain_entry

Weblog files may contain the domain name (eg in case a system hosts several webserver) as 10th column. This domain name may be missing, which is the expectation of method "logs_to_df()

But sometimes the field appears in a weblog file, as an entry or an empty entry (eg '-' or '"-"').  logs_to_df() cannot handle this extra field and ignores these entries.

## 2) Failure on escaped quotes (\\")

In weblogs quotes mark fields. Sometimes quotes are part of a field string and escaped by "\\". logs_to_df() does not catch escaped character \\" and ignores these entries.

**Comment by eliasdabbas** [comment]
Thanks @Dibal 

The `logs_to_df` function comes with a set of default log formats, and their regular expressions that match them (see below).

There are many other formats and the default formats can be customized. So the function accepts any regex for the `log_format` paramater. 

If your file is different, you can use (and modify) any of the supported formats. Otherwise you can write a new regex for your specific format. 

You can get all the formats as a dictionary:
```python
import advertools as adv
adv.logs.LOG_FORMATS

```
Here they are:

```
log format: common
^(?P<client>\S+) \S+ (?P<userid>\S+) \[(?P<datetime>[^\]]+)\] "(?P<method>[A-Z]+) (?P<request>[^ "]+)? HTTP/[0-9.]+" (?P<status>[0-9]{3}) (?P<size>[0-9]+|-)$


log format: combined
^(?P<client>\S+) \S+ (?P<userid>\S+) \[(?P<datetime>[^\]]+)\] "(?P<method>[A-Z]+) (?P<request>[^ "]+)? HTTP/[0-9.]+" (?P<status>[0-9]{3}) (?P<size>[0-9]+|-) "(?P<referrer>[^"]*)" "(?P<useragent>[^"]*)"\s*$


log format: common_with_vhost
^(?P<vhost>\S+) (?P<client>\S+) \S+ (?P<userid>\S+) \[(?P<datetime>[^\]]+)\] "(?P<method>[A-Z]+) (?P<request>[^ "]+)? HTTP/[0-9.]+" (?P<status>[0-9]{3}) (?P<size>[0-9]+|-)$


log format: nginx_error
^(?P<datetime>\d{4}/\d\d/\d\d \d\d:\d\d:\d\d) \[(?P<level>[^\]]+)\] (?P<pid>\d+)#(?P<tid>\d+): (?P<counter>\*\d+ | )?(?P<message>.*)


log format: apache_error
^(?P<datetime>\[[^\]]+\]) (?P<level>\[[^\]]+\]) \[pid (?P<pid>\d+)\] (?P<file>\S+):(?P<status> \S+| ):? \[client (?P<client>\S+)\] (?P<message>.*)

```

Please let me know if you still have issues.

**Comment by Dibal** [comment]
Thanks a lot! I had no idea how the regex should look like and no idea by the nice apporach of "adv.logs.LOG_FORMATS". This variable is not defined in the manual.

I simply inserted `(?P<domain>\S+)` to the "combined" regex string, added a list of 10 entry names -- and `logs_to_df` works like a charm.

I further tried to catch escaped quotes via `[^"\\]|\\.*` -- but I failed. These extra quotes confuse and I deleted all '\"' entries in advance.

PS: Suggestion for improving "UX": instead of one string for "regex" logs_to_df may accept a list as well, one expression for each entry. If not specified logs_to_df could derive column names as "0", "1" .. "len(list)".

**Comment by eliasdabbas** [comment]
Happy to know that it worked fine. 

Documentation actually mentions the regex as well as `LOG_FORMATS`: 

<img width="701" alt="Screenshot 2024-02-09 at 11 27 12 PM" src="https://github.com/eliasdabbas/advertools/assets/15708966/73a63e5d-1920-4a6c-8b82-2767c235fe30">

Happy to make changes if you have suggestions on improving the documentation. 

> I simply inserted (?P<domain>\S+) to the "combined" regex string, added a list of 10 entry names

Can you please clarify what you mean by adding 10 entry names?

> instead of one string for "regex" logs_to_df may accept a list as well, one expression for each entry

Do you mean a list of regexes each for status, size, method, etc.? 
If so, how would that help? You can combine them together in one regex easily. 
Otherwise, please clarify.

**Comment by Dibal** [comment]
It is fine as it is after it is clear how to handle.

Otherwise following approach may be more obvious and more fault tolerant:

1. Instead of one regex_string  -> a list of regex_string_elements where each element catches one column. Eg if only 9 regex_string_elements are given only 9 columns are created. If one regex_string_element is wrong this column does not collect entries.
2. The parameter `fields`_list_of_strings_ might become optional. In case it is missing or incomplete it creates column names itself (eg ['client', 'userid'] -> ['client', 'userid', ' 3', '4', ...].

(1) would help to reuse `LOG_FORMATS`. Example
~~~
myformat = LOG_FORMATS["combined"]
myformat.append('new_regex_string_element')
myformat[3] = 'replaceby_new_regex_string_element'
~~~

(2) avoids error message if user has no idea about this entry. If she is not happy with names like '3' or '4', she may check this parameter.

**Comment by eliasdabbas** [comment]
For point 1: 
I don't think it would work because the lines of log files are single strings each, and have to be parsed as a whole. If they were a list of strings your approach would be great. 

Point2: It's already optional. Each log format comes with a list of columns names. You only need to supply this if you provide a regex that is not one of the default log formats.

You can already reuse the log formats (that is why they include names, so it is clear what they match).

Thanks again.
